# Generated by Django 5.1.6 on 2025-03-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desprenoi_BC_Biroul_executiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poza', models.ImageField(null=True, upload_to='')),
                ('nume', models.TextField(null=True)),
                ('functia', models.TextField(null=True)),
                ('link_facebook', models.TextField(null=True)),
                ('link_instagram', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desprenoi_BC_Comisia_de_cenzori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poza', models.ImageField(null=True, upload_to='')),
                ('nume', models.TextField(null=True)),
                ('functia', models.TextField(null=True)),
                ('link_facebook', models.TextField(null=True)),
                ('link_instagram', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desprenoi_BC_Coordonatori_Departamente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poza', models.ImageField(null=True, upload_to='')),
                ('nume', models.TextField(null=True)),
                ('functia', models.TextField(null=True)),
                ('link_facebook', models.TextField(null=True)),
                ('link_instagram', models.TextField(null=True)),
            ],
        ),
    ]
