# Generated by Django 5.1.6 on 2025-03-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DespreNoi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desprenoi_bc_biroul_executiv',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desprenoi_bc_comisia_de_cenzori',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desprenoi_bc_coordonatori_departamente',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
