# Generated by Django 5.1.6 on 2025-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DespreNoi', '0002_desprenoi_bc_biroul_executiv_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desprenoi_bc_biroul_executiv',
            name='poza',
            field=models.ImageField(null=True, upload_to='desprenoi/bc/bex'),
        ),
        migrations.AlterField(
            model_name='desprenoi_bc_comisia_de_cenzori',
            name='poza',
            field=models.ImageField(null=True, upload_to='desprenoi/bc/cc'),
        ),
        migrations.AlterField(
            model_name='desprenoi_bc_coordonatori_departamente',
            name='poza',
            field=models.ImageField(null=True, upload_to='desprenoi/bc/bc'),
        ),
    ]
