# Generated by Django 5.1.6 on 2025-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0003_parteneri_img_testimoniale_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcasaPozaOrganizatiiPartenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='SiteApp/Parteneri')),
                ('text', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcasaPozaPrincipala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='SiteApp/poze/acasa/pozaprincipala')),
            ],
        ),
        migrations.CreateModel(
            name='AcasaTestimoniale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='SiteApp/poze/acasa/pozaTestimonial')),
                ('testimonial', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Parteneri',
        ),
        migrations.DeleteModel(
            name='Testimoniale',
        ),
    ]
