# Generated by Django 5.1.6 on 2025-03-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0005_alter_acasapozaorganizatiipartenere_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcasaPozaOrganizatiiPartenere',
            new_name='AcasaOrganizatiiPartenere',
        ),
    ]
