# Generated by Django 5.1.6 on 2025-03-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0006_rename_acasapozaorganizatiipartenere_acasaorganizatiipartenere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acasaorganizatiipartenere',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='acasapozaprincipala',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='acasatestimoniale',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
