# Generated by Django 5.1.6 on 2025-03-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0007_alter_acasaorganizatiipartenere_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acasaorganizatiipartenere',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acasapozaprincipala',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acasatestimoniale',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
