# Generated by Django 5.1.6 on 2025-03-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0008_acasaorganizatiipartenere_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acasaorganizatiipartenere',
            old_name='text',
            new_name='alt',
        ),
        migrations.AddField(
            model_name='acasaorganizatiipartenere',
            name='nume',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='acasaorganizatiipartenere',
            name='site',
            field=models.TextField(null=True),
        ),
    ]
