# Generated by Django 5.1.6 on 2025-03-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0009_rename_text_acasaorganizatiipartenere_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumerePaginaPrincipala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.IntegerField(default=0)),
                ('text', models.TextField(null=True)),
                ('ordine', models.IntegerField(default=0)),
            ],
        ),
    ]
