# Generated by Django 5.1.6 on 2025-03-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0010_numerepaginaprincipala'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumerePaginaPrincipala',
        ),
    ]
