# Generated by Django 5.1.6 on 2025-03-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0011_delete_numerepaginaprincipala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acasatestimoniale',
            old_name='testimonial',
            new_name='title',
        ),
    ]
