# Generated by Django 5.1.6 on 2025-03-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0012_rename_testimonial_acasatestimoniale_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('numar', models.IntegerField(default=0)),
            ],
        ),
    ]
