# Generated by Django 5.1.6 on 2025-03-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0014_numere_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numere',
            name='numar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
