# Generated by Django 5.1.6 on 2025-03-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0015_alter_numere_numar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Persoane_de_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255, null=True)),
                ('functia', models.TextField(null=True)),
                ('numar_de_telefon', models.IntegerField(default=0)),
                ('email', models.TextField(null=True)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Numere',
            new_name='Pagina_Principala_Numere',
        ),
        migrations.RenameModel(
            old_name='AcasaOrganizatiiPartenere',
            new_name='Pagina_Principala_OrganizatiiPartenere',
        ),
        migrations.RenameModel(
            old_name='AcasaPozaPrincipala',
            new_name='Pagina_Principala_PozaPrincipala',
        ),
        migrations.RenameModel(
            old_name='AcasaTestimoniale',
            new_name='Pagina_Principala_Testimoniale',
        ),
    ]
