# Generated by Django 5.1.6 on 2025-03-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0016_contact_persoane_de_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_persoane_de_contact',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
