# Generated by Django 5.1.6 on 2025-03-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0017_contact_persoane_de_contact_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_persoane_de_contact',
            name='title',
        ),
    ]
