# Generated by Django 5.1.6 on 2025-03-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0018_remove_contact_persoane_de_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_persoane_de_contact',
            name='numar_de_telefon',
            field=models.TextField(default=0),
        ),
    ]
